from django.urls import path

from .views import (
    attendance_audit_history,
    attendance_dashboard,
    attendance_history,
    batch_attendance_detail,
    create_attendance,
    delete_attendance,
    export_attendance_csv,
    export_attendance_excel,
    export_attendance_pdf,
    export_batch_report,
    gps_attendance_page,
    gps_check_in,
    gps_check_out,
    intern_attendance_detail,
    intern_dashboard,
    scan_attendance,
    scanner_page,
    update_attendance,
)


urlpatterns = [
    path("intern/dashboard/", intern_dashboard, name="intern-dashboard"),
    path(
        "dashboard/",
        attendance_dashboard,
        name="attendance-dashboard",
    ),
    path(
        "scanner/",
        scanner_page,
        name="scanner-page",
    ),
    path(
        "scan/<uuid:qr_code>/",
        scan_attendance,
        name="scan-attendance",
    ),
    path(
        "gps/",
        gps_attendance_page,
        name="gps-attendance",
    ),
    path(
        "gps/check-in/",
        gps_check_in,
        name="gps-check-in",
    ),
    path(
        "gps/check-out/",
        gps_check_out,
        name="gps-check-out",
    ),
    path(
        "history/",
        attendance_history,
        name="attendance-history",
    ),
    path(
        "create/",
        create_attendance,
        name="attendance-create",
    ),
    path(
        "<int:attendance_id>/edit/",
        update_attendance,
        name="attendance-update",
    ),
    path(
        "<int:attendance_id>/delete/",
        delete_attendance,
        name="attendance-delete",
    ),
    path(
        "audit/",
        attendance_audit_history,
        name="attendance-audit-history",
    ),
    path(
        "interns/<int:intern_id>/",
        intern_attendance_detail,
        name="intern-attendance-detail",
    ),
    path(
        "batches/<int:batch_id>/",
        batch_attendance_detail,
        name="batch-attendance-detail",
    ),
    path(
        "reports/export/csv/",
        export_attendance_csv,
        name="attendance-export-csv",
    ),
    path(
        "reports/export/excel/",
        export_attendance_excel,
        name="attendance-export-excel",
    ),
    path(
        "reports/export/pdf/",
        export_attendance_pdf,
        name="attendance-export-pdf",
    ),
    path(
        "reports/<int:batch_id>/csv/",
        export_batch_report,
        name="attendance-report-csv",
    ),
]