# Generated by Django 6.0.7 on 2026-07-15 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0002_session_internprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internprofile',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='interns.batch'),
        ),
        migrations.AlterField(
            model_name='internprofile',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='interns.session'),
        ),
    ]
