# Generated by Django 6.0.7 on 2026-07-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interns', '0004_approvalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='internprofile',
            name='qr_code',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
