# Generated by Django 6.0.7 on 2026-07-20 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='recipient',
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ATTENDANCE_CHECK_IN', 'Attendance check-in'), ('ATTENDANCE_CHECK_OUT', 'Attendance check-out'), ('ATTENDANCE_LATE', 'Late attendance'), ('ATTENDANCE_ABSENT', 'Absent attendance'), ('ATTENDANCE_UPDATED', 'Attendance updated'), ('ATTENDANCE_DELETED', 'Attendance deleted'), ('GPS_REJECTED', 'GPS attendance rejected'), ('GENERAL', 'General')], default='GENERAL', max_length=40),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_86ea8b_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'created_at'], name='notificatio_notific_f2e0f7_idx'),
        ),
    ]
