# Generated by Django 6.0.7 on 2026-07-19 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('interns', '0005_internprofile_qr_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted')], max_length=20)),
                ('previous_status', models.CharField(blank=True, choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent')], max_length=20, null=True)),
                ('new_status', models.CharField(blank=True, choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent')], max_length=20, null=True)),
                ('previous_check_in_time', models.TimeField(blank=True, null=True)),
                ('new_check_in_time', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_daily_attendance',
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='interns.batch'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='interns.internprofile'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='interns.session'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['attendance_date', 'status'], name='attendance__attenda_f3ac94_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['batch', 'attendance_date'], name='attendance__batch_i_f0bf39_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['session', 'attendance_date'], name='attendance__session_6a446f_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('intern', 'session', 'attendance_date'), name='unique_intern_session_attendance_date'),
        ),
        migrations.AddField(
            model_name='attendanceaudit',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='attendance.attendance'),
        ),
        migrations.AddField(
            model_name='attendanceaudit',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_audits', to='interns.batch'),
        ),
        migrations.AddField(
            model_name='attendanceaudit',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_audits', to='interns.internprofile'),
        ),
        migrations.AddField(
            model_name='attendanceaudit',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceaudit',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_audits', to='interns.session'),
        ),
        migrations.AddIndex(
            model_name='attendanceaudit',
            index=models.Index(fields=['action', 'created_at'], name='attendance__action_ba0cee_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceaudit',
            index=models.Index(fields=['intern', 'attendance_date'], name='attendance__intern__8f7152_idx'),
        ),
    ]
