# Generated by Django 6.0.7 on 2026-07-19 20:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendanceaudit_and_more'),
        ('interns', '0005_internprofile_qr_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('radius_metres', models.DecimalField(decimal_places=2, default=100, help_text='Maximum permitted distance from this location, measured in metres.', max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('maximum_accuracy_metres', models.DecimalField(decimal_places=2, default=50, help_text='Maximum acceptable browser GPS accuracy, measured in metres.', max_digits=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_method',
            field=models.CharField(choices=[('GPS', 'GPS'), ('QR', 'QR Code'), ('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], default='QR', max_length=20),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in metres.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_accuracy',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in metres.', max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='attendance',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceaudit',
            name='new_attendance_method',
            field=models.CharField(blank=True, choices=[('GPS', 'GPS'), ('QR', 'QR Code'), ('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendanceaudit',
            name='new_check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendanceaudit',
            name='previous_attendance_method',
            field=models.CharField(blank=True, choices=[('GPS', 'GPS'), ('QR', 'QR Code'), ('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='attendanceaudit',
            name='previous_check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='attendance.attendancelocation'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['attendance_method', 'attendance_date'], name='attendance__attenda_4a8a6b_idx'),
        ),
    ]
