# Generated by Django 6.0.7 on 2026-07-23 09:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancelocation_attendance_attendance_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelocation',
            name='latitude',
            field=models.DecimalField(decimal_places=20, max_digits=20, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='attendancelocation',
            name='longitude',
            field=models.DecimalField(decimal_places=20, max_digits=20, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AlterField(
            model_name='attendancelocation',
            name='maximum_accuracy_metres',
            field=models.DecimalField(decimal_places=4, default=50, help_text='Maximum acceptable browser GPS accuracy, measured in metres.', max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='attendancelocation',
            name='radius_metres',
            field=models.DecimalField(decimal_places=4, default=100, help_text='Maximum permitted distance from this location, measured in metres.', max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
